name: dart_numerics
description: An ultimate numerical package for Dart for professional and every day use.
version: 0.0.7-SNAPSHOT
homepage: https://github.com/zlumyo/dart_numerics

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.20.0
